# Generated by Django 4.2.7 on 2023-12-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('sender_id', models.TextField(primary_key=True, serialize=False)),
                ('language', models.TextField(default='vn')),
            ],
        ),
    ]
