# Generated by Django 4.2.7 on 2023-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sum_reservation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
