# Generated by Django 4.2.7 on 2023-12-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.TextField(default='livechat'),
        ),
        migrations.AddField(
            model_name='history',
            name='channel',
            field=models.TextField(default='livechat'),
        ),
    ]
