# Generated by Django 4.2.7 on 2023-12-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_channel_history_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='channel',
        ),
    ]
